version: '3'
networks:
  default:
    name: rhub-development
services:
  api:
    image: registry.access.redhat.com/ubi8/python-38
    volumes:
      - .:/rhub-api
    environment:
      - PYTHONPATH=/rhub-api/packages:/rhub-api/src
      - PYTHONDONTWRITEBYTECODE=yeah
    ports:
      - 8081:5000
    working_dir: /rhub-api
    command: ["./bin/flask"]
